[build-system]
requires = [
    "hatchling==1.31.0",
    "hatch-vcs==0.5.0",
]
build-backend = "hatchling.build"

[project]
name = "pothenon"
description = "pothenon - dependency parser for python functions"
readme = "docs/README.md"
keywords = [ "pyiron",]
requires-python = ">=3.11, <3.14"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "gitpython==3.1.58",
    "pyiron_snippets==1.4.0",
]
dynamic = [ "version",]
authors = [
    { name = "Sam Waseda", email = "waseda@mpie.de" },
]

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://pyiron.org/"
Documentation = "https://pothenon.readthedocs.io"
Repository = "https://github.com/pyiron/pothenon"

[tool.hatch.build]
include = [
    "pothenon"
]

[tool.hatch.build.hooks.vcs]
version-file = "pothenon/_version.py"

[tool.hatch.build.targets.sdist]
include = [
    "pothenon"
]

[tool.hatch.build.targets.wheel]
packages = [
    "pothenon"
]

[tool.hatch.version]
source = "vcs"
path = "pothenon/_version.py"

[tool.ruff]
exclude = ["docs", "notebooks"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["E501"] #ignore line-length violations

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in init files -- we specify APIs this way

[tool.black]
extend-exclude = '''
(
  ^/docs
)
'''
